spring.application.name=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# C\u1EA5u h\u00ECnh CSDL (C\u1EA7n thi\u1EBFt cho b\u01B0\u1EDBc test ti\u1EBFp theo)
spring.datasource.url=jdbc:mysql://localhost:3307/auth_service
spring.datasource.username=root
spring.datasource.password=root

# B\u00E1o cho Hibernate kh\u00F4ng t\u1EF1 t\u1EA1o b\u1EA3ng (\u0111\u1EC3 Flyway lo)
spring.jpa.hibernate.ddl-auto=none

# B\u00E1o cho Flyway t\u1EA1o baseline khi CSDL \u0111\u00E3 c\u00F3 s\u1EB5n b\u1EA3ng
spring.flyway.baseline-on-migrate=true

application.security.jwt.expiration-ms=86400000

application.security.jwt.secret-key=6B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hunggk2004@gmail.com
spring.mail.password=hpbhdsxilbzoevmr

spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.initial-instance-info-replication-interval-seconds=10
eureka.client.registry-fetch-interval-seconds=10
