server.port=8082
spring.application.name=order-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3309/order_service
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=false
# Security
application.security.jwt.secret-key=6B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.initial-instance-info-replication-interval-seconds=10
eureka.client.registry-fetch-interval-seconds=10