server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  cloud:
    gateway:
      # Cấu trúc mới yêu cầu khai báo rõ 'server.webflux' cho ứng dụng Reactive
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            # 1. USER-SERVICE
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**, /api/users/**, /api/restaurants/**

            # 2. CATALOG-SERVICE
            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/api/catalog/**, /api/catalog/uploads/**

            # 3. ORDER-SERVICE
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**, /api/reports/**

            # 4. NOTIFICATION-SERVICE
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notifications/**, /ws/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

            # 5. INTEGRATION-SERVICE
            - id: integration-service
              uri: lb://INTEGRATION-SERVICE
              predicates:
                - Path=/api/integration/**