server:
  port: ${NOTIFICATION_SERVICE_PORT:0}
  
spring:
  datasource:
    url: jdbc:mysql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:3309}/${ORDER_DB_NAME:order_service}
    username: ${ORDER_DB_USERNAME:root}
    password: ${ORDER_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: false
    # baseline-on-migrate: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:6B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A}

springdoc:
  api-docs:
    path: /api/order/v3/api-docs
  swagger-ui:
    enabled: false